import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const cursive = localFont({
  src: [
    {
      path: "./fonts/IRANSansBold.ttf",
      style: "bold",
      weight: "700",
    },
    {
      path: "./fonts/IRANSansRegular.ttf",
      style: "normal",
      weight: "400",
    },
    {
      path: "./fonts/IRANSansLight.ttf",
      style: "light",
      weight: "300",
    },
    {
      path: "./fonts/IRANSansUltraLight.ttf",
      style: "ultraLight",
      weight: "100",
    },
  ],
  variable: "--font-cursive",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1.0",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="fa">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={`${cursive.variable}`}>{children}</body>
    </html>
  );
}
