import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const cursive = localFont({
  src: [
    {
      path: "./fonts/IRANSansBold.ttf",
      style: "bold",
      weight: "700",
    },
    {
      path: "./fonts/IRANSansRegular.ttf",
      style: "normal",
      weight: "400",
    },
    {
      path: "./fonts/IRANSansLight.ttf",
      style: "light",
      weight: "300",
    },
    {
      path: "./fonts/IRANSansUltraLight.ttf",
      style: "ultraLight",
      weight: "100",
    },
  ],
  variable: "--font-cursive",
  display: "swap",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="fa">
      <body className={`${cursive.variable}`}>{children}</body>
    </html>
  );
}
